import { Job } from "@/lib/types";

export const valueOptions = [
  "Diversity & inclusion",
  "Impactful work",
  "Independence & autonomy",
  "Innovative product & tech",
  "Mentorship & career development",
  "Progressive leadership",
  "Recognition & reward",
  "Role mobility",
  "Social responsibility & sustainability",
  "Transparency & communication",
  "Work-life balance",
];

export const roleFamilies: Record<string, string[]> = {
  "Technical & Engineering": [
    "Aerospace Engineering",
    "AI & Machine Learning",
    "Architecture & Civil Engineering",
    "Data & Analytics",
    "Developer Relations",
    "DevOps & Infrastructure",
    "Electrical Engineering",
    "Engineering Management",
    "Hardware Engineering",
    "IT & Security",
    "Mechanical Engineering",
    "Process Engineering",
    "QA & Testing",
    "Software Engineering",
  ],
  "Finance & Operations & Strategy": [
    "Accounting",
    "Business Strategy",
    "Consulting",
    "Finance & Banking",
    "Growth & Marketing",
    "Operations & Logistics",
    "Product",
    "Real Estate",
    "Retail",
  ],
  "Creative & Design": [
    "Art, Graphics & Animation",
    "Audio & Sound Design",
    "Content & Writing",
    "Creative Production",
    "Journalism",
    "Social Media",
    "UI/UX & Design",
  ],
  "Education & Training": ["Education", "Training"],
  "Legal & Support & Administration": [
    "Administrative & Executive Assistance",
    "Clerical & Data Entry",
    "Customer Experience & Support",
    "Legal & Compliance",
    "People & HR",
    "Security & Protective Services",
  ],
  "Life Sciences": ["Biology & Biotech", "Lab & Research", "Medical, Clinical & Veterinary"],
};

export const aiSpecializations = [
  "AI Research",
  "Applied Machine Learning",
  "Computer Vision",
  "Conversational AI & Chatbots",
  "Deep Learning",
  "Natural Language Processing (NLP)",
  "Robotics & Autonomous Systems",
  "Speech Recognition",
];

export const locationOptions: Record<string, string[]> = {
  "United States": [
    "Atlanta",
    "Austin",
    "Baltimore",
    "Boston",
    "Charlotte",
    "Chicago",
    "Dallas",
    "Denver",
    "Las Vegas",
    "Los Angeles",
    "Miami",
    "New York City",
    "Philadelphia",
    "Phoenix",
    "Portland",
    "Remote in USA",
    "San Diego",
    "San Francisco Bay Area",
    "Seattle",
    "Washington D.C.",
  ],
  Canada: ["Montreal", "Ottawa", "Quebec City", "Remote in Canada", "Toronto", "Vancouver", "Winnipeg"],
  "United Kingdom": ["Birmingham", "Liverpool", "London", "Manchester", "Remote in UK"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth", "Remote in Australia"],
};

export const roleLevelOptions = [
  "Internship",
  "Entry Level & New Grad",
  "Junior (1 to 2 years)",
  "Mid-level (3 to 4 years)",
  "Senior (5 to 8 years)",
  "Expert & Leadership (9+ years)",
];

export const leadershipOptions = ["Individual Contributor", "Manager", "I do not have a preference"];

export const companySizeOptions = [
  "1-10 employees",
  "11-50 employees",
  "51-200 employees",
  "201-500 employees",
  "501-1,000 employees",
  "1,001-5,000 employees",
  "5,001-10,000 employees",
  "10,001+ employees",
];

export const industries = [
  "Aerospace",
  "AI & Machine Learning",
  "Automotive & Transportation",
  "Biotechnology",
  "Consulting",
  "Consumer Goods",
  "Consumer Software",
  "Crypto & Web3",
  "Cybersecurity",
  "Data & Analytics",
  "Defense",
  "Design",
  "Education",
  "Energy",
  "Enterprise Software",
  "Entertainment",
  "Financial Services",
  "Fintech",
  "Food & Agriculture",
  "Gaming",
  "Government & Public Sector",
  "Hardware",
  "Healthcare",
  "Industrial & Manufacturing",
  "Legal",
  "Quantitative Finance",
  "Real Estate",
  "Robotics & Automation",
  "Social Impact",
  "Venture Capital",
  "VR & AR",
];

export const skillPool = [
  "Business Analytics",
  "Excel/Numbers/Sheets",
  "Git",
  "HTML/CSS",
  "Java",
  "MailChimp",
  "MATLAB",
  "Operations Research",
  "Python",
  "SEO",
  "Zendesk",
  "TypeScript",
  "React",
  "Node.js",
  "SQL",
  "AWS",
  "PyTorch",
  "TensorFlow",
  "Data Visualization",
  "Product Thinking",
  "Docker",
  "Kubernetes",
  "PostgreSQL",
  "GraphQL",
  "Redis",
  "Spark",
  "dbt",
  "Tableau",
  "LLM",
  "Prompt Engineering",
  "MLflow",
];

// ── Expanded mock job dataset (8 jobs across categories) ─────────────────────

export const mockJobs: Job[] = [
  {
    jobId: "job_1",
    title: "AI Engineer",
    company: "Siena AI",
    companySize: "51-200 employees",
    level: ["Mid", "Senior"],
    locations: ["London, UK", "Toronto, ON, Canada", "Remote"],
    categories: ["Applied Machine Learning", "Natural Language Processing (NLP)", "AI & Machine Learning"],
    requiredSkills: ["LLM", "Machine Learning", "Python", "NLP"],
    summary:
      "Build production-grade conversational AI that handles millions of customer interactions daily. Strong LLM and NLP engineering background required.",
    requirements: [
      "3+ years building AI products using LLMs and NLP technologies",
      "Strong Python engineering and debugging skills",
      "Ability to communicate technical ideas clearly to mixed audiences",
      "Experience deploying models to production with monitoring and rollback plans",
    ],
    responsibilities: [
      "Lead development and experimentation of new conversational AI features",
      "Deploy AI technologies into core customer service products",
      "Collaborate across engineering and product teams on LLM pipelines",
      "Stay current with state-of-the-art LLM research and tooling",
    ],
    desiredQualifications: [
      "Experience with React, TypeScript, Node.js, Postgres",
      "Exposure to data pipeline technologies like Spark or dbt",
      "Broad systems architecture understanding",
    ],
    fullPosting:
      "Siena AI seeks an AI Engineer to build production-grade conversational AI capabilities. You will own experiments, productionization, and cross-functional collaboration from ideation through rollout. Join a fast-moving team where your work directly shapes customer experiences at scale.",
  },
  {
    jobId: "job_2",
    title: "Machine Learning Engineer",
    company: "Notion",
    companySize: "1,001-5,000 employees",
    salary: "$180,000 - $230,000",
    level: ["Mid", "Senior"],
    locations: ["San Francisco, CA", "Remote in USA"],
    categories: ["Machine Learning", "Platform"],
    requiredSkills: ["Python", "Distributed Systems", "LLM", "PyTorch"],
    summary:
      "Build ML systems that power smart features for 30M+ users. Own the ML platform from training to serving, including vector search and recommendation.",
    requirements: [
      "Hands-on ML model development and deployment in production",
      "Strong backend engineering and distributed systems foundations",
      "Experience with experimentation infrastructure and metrics",
      "Knowledge of model evaluation, A/B testing, and rollback strategies",
    ],
    responsibilities: [
      "Ship ML-powered user-facing features such as smart search and AI writer",
      "Create reliable model-serving and inference infrastructure",
      "Improve retrieval quality using vector search techniques",
      "Partner with research to productionize new model architectures",
    ],
    desiredQualifications: [
      "Experience with vector databases (Pinecone, Weaviate, pgvector)",
      "Background in building model evaluation frameworks",
      "Familiarity with fine-tuning and RLHF workflows",
    ],
    fullPosting:
      "As an ML Engineer at Notion, you will work at the intersection of product and platform to deliver intelligence capabilities that millions rely on daily. You will own end-to-end ML pipelines, collaborate with product teams, and raise the quality bar for AI in Notion.",
  },
  {
    jobId: "job_3",
    title: "Senior Data Scientist",
    company: "Stripe",
    companySize: "5,001-10,000 employees",
    salary: "$170,000 - $220,000",
    level: ["Senior"],
    locations: ["San Francisco, CA", "New York City, NY", "Remote in USA"],
    categories: ["Data & Analytics", "Machine Learning", "Fintech"],
    requiredSkills: ["Python", "SQL", "Statistical Modeling", "Machine Learning", "Spark"],
    summary:
      "Apply data science to improve fraud detection, credit risk, and payment optimization for millions of businesses worldwide.",
    requirements: [
      "5+ years of data science or ML experience in a production environment",
      "Expert-level Python and SQL for large-scale data analysis",
      "Strong foundation in statistical modeling, causal inference, and experimentation",
      "Experience with big data tools (Spark, Hive, or equivalent)",
    ],
    responsibilities: [
      "Build and maintain fraud and risk models deployed globally",
      "Design and analyze A/B experiments that drive product decisions",
      "Partner with engineers to productionize models at scale",
      "Communicate findings to senior leadership and cross-functional stakeholders",
    ],
    desiredQualifications: [
      "Domain experience in financial risk, fraud, or payments",
      "Experience with causal inference or uplift modeling",
      "Background in NLP for transaction categorization",
    ],
    fullPosting:
      "Stripe's Data Science team works on some of the most consequential ML problems in fintech — fraud prevention, credit risk, and intelligent routing serving millions of businesses. Join a rigorous, impact-driven team where your models directly affect the global economy.",
  },
  {
    jobId: "job_4",
    title: "Senior Backend Engineer",
    company: "Linear",
    companySize: "51-200 employees",
    salary: "$160,000 - $210,000",
    level: ["Senior"],
    locations: ["Remote"],
    categories: ["Software Engineering", "Enterprise Software"],
    requiredSkills: ["TypeScript", "Node.js", "PostgreSQL", "GraphQL", "Redis"],
    summary:
      "Build the infrastructure that powers Linear's project management platform, used by engineering teams at thousands of companies globally.",
    requirements: [
      "5+ years of backend engineering with Node.js and TypeScript",
      "Deep expertise in PostgreSQL query optimization and schema design",
      "Experience building and operating production APIs at scale",
      "Strong understanding of distributed systems and eventual consistency",
    ],
    responsibilities: [
      "Own and evolve core backend services including sync engine and search",
      "Design schema and query patterns for high-throughput collaborative features",
      "Improve reliability, latency, and observability of production systems",
      "Mentor junior engineers and drive architectural decisions",
    ],
    desiredQualifications: [
      "Experience with real-time collaboration (CRDTs, operational transforms)",
      "Background in building developer tools or productivity software",
      "Open-source contributions relevant to the stack",
    ],
    fullPosting:
      "Linear is building the project management tool that engineers actually love. Our Backend team owns the systems that make real-time sync, search, and scale possible. You will work in a lean, autonomous team focused on craft and shipping quality work.",
  },
  {
    jobId: "job_5",
    title: "Product Manager — AI Features",
    company: "Figma",
    companySize: "1,001-5,000 employees",
    salary: "$180,000 - $230,000",
    level: ["Senior"],
    locations: ["San Francisco, CA", "New York City, NY"],
    categories: ["Product", "AI & Machine Learning", "Design"],
    requiredSkills: ["Product Management", "AI/ML Fluency", "User Research", "Data Analysis"],
    summary:
      "Lead the product strategy for AI-powered design features used by 4M+ designers. Bridge ML research and product delivery.",
    requirements: [
      "5+ years of product management experience at a product-led company",
      "Demonstrated ability to ship AI or ML-powered features to broad audiences",
      "Strong data analysis and user research skills",
      "Excellent written and verbal communication for leadership audiences",
    ],
    responsibilities: [
      "Own the AI features roadmap, from ideation through launch and iteration",
      "Work closely with ML engineers and design researchers to define scope",
      "Define success metrics and continuously optimize based on data",
      "Represent user needs to engineering and ML teams",
    ],
    desiredQualifications: [
      "Design tool or creative software background",
      "Experience with generative AI or multimodal models",
      "Strong network in the design community",
    ],
    fullPosting:
      "As PM for AI Features at Figma, you will chart the course for how AI augments creativity. You own discovery, prioritization, and delivery of AI capabilities that help designers move faster and create better work. This is a high-visibility, high-impact role at the frontier of design and AI.",
  },
  {
    jobId: "job_6",
    title: "Data Analyst",
    company: "Duolingo",
    companySize: "1,001-5,000 employees",
    salary: "$100,000 - $135,000",
    level: ["Mid"],
    locations: ["Pittsburgh, PA", "Remote in USA"],
    categories: ["Data & Analytics", "Consumer Software", "Education"],
    requiredSkills: ["SQL", "Python", "Data Visualization", "Statistical Analysis", "Tableau"],
    summary:
      "Turn Duolingo's massive learning dataset into actionable insights that improve engagement, retention, and learning outcomes for 500M learners.",
    requirements: [
      "3+ years of data analysis in a high-growth consumer product company",
      "Expert-level SQL and Python (pandas, numpy) for data manipulation",
      "Experience designing and analyzing A/B experiments",
      "Strong data visualization and storytelling skills",
    ],
    responsibilities: [
      "Analyze learning behavior data to surface engagement and retention drivers",
      "Build and maintain dashboards for product, growth, and leadership teams",
      "Partner with product managers on experiment design and result interpretation",
      "Develop models to predict and reduce churn",
    ],
    desiredQualifications: [
      "Experience with educational technology or gamification data",
      "Background in behavioral economics or learning science",
      "Familiarity with Looker or dbt",
    ],
    fullPosting:
      "Duolingo's Analytics team helps the world's most popular language app understand how people learn. You will work with rich behavioral datasets, collaborate with world-class researchers, and directly improve the experience for hundreds of millions of learners.",
  },
  {
    jobId: "job_7",
    title: "Frontend Engineer — Design System",
    company: "Vercel",
    companySize: "201-500 employees",
    salary: "$150,000 - $195,000",
    level: ["Mid", "Senior"],
    locations: ["Remote"],
    categories: ["Software Engineering", "UI/UX & Design", "Developer Tools"],
    requiredSkills: ["TypeScript", "React", "CSS", "Accessibility", "Design Systems"],
    summary:
      "Own and grow Vercel's design system used by internal teams and open-sourced for the community. Bridge design and engineering at a developer-focused company.",
    requirements: [
      "4+ years of frontend engineering with React and TypeScript",
      "Deep expertise in CSS, design tokens, and responsive layouts",
      "Strong understanding of web accessibility (WCAG 2.1 AA) and ARIA",
      "Experience maintaining or contributing to a component library or design system",
    ],
    responsibilities: [
      "Build, document, and evolve accessible, production-quality UI components",
      "Define and maintain design tokens and theming system",
      "Partner with designers to translate Figma specs into reusable components",
      "Establish contribution guidelines and review component PRs from the team",
    ],
    desiredQualifications: [
      "Experience publishing open-source npm packages",
      "Contributions to popular UI libraries (Radix, shadcn, Headless UI)",
      "Background in animation and micro-interaction design",
    ],
    fullPosting:
      "Vercel is looking for a Frontend Engineer to work on the design system that powers our dashboard, marketing site, and community tools. You will work remotely alongside world-class designers, and your components will be used daily by millions of developers.",
  },
  {
    jobId: "job_8",
    title: "DevOps / Platform Engineer",
    company: "Anthropic",
    companySize: "201-500 employees",
    salary: "$170,000 - $225,000",
    level: ["Senior"],
    locations: ["San Francisco, CA", "Remote in USA"],
    categories: ["DevOps & Infrastructure", "AI & Machine Learning", "Platform"],
    requiredSkills: ["Kubernetes", "AWS", "Terraform", "Docker", "Python", "CI/CD"],
    summary:
      "Build the compute and deployment infrastructure that trains and serves state-of-the-art AI models used in Claude and the Anthropic API.",
    requirements: [
      "5+ years of platform or infrastructure engineering",
      "Expert-level Kubernetes and AWS (EKS, EC2, S3, IAM)",
      "Strong Terraform or Pulumi infrastructure-as-code skills",
      "Experience with high-throughput GPU or ML workloads at scale",
    ],
    responsibilities: [
      "Design and operate Kubernetes clusters for large-scale model training and serving",
      "Build CI/CD pipelines and deployment automation for ML systems",
      "Improve observability with metrics, logging, and alerting",
      "Collaborate with ML researchers to provide reliable compute infrastructure",
    ],
    desiredQualifications: [
      "Experience with NVIDIA GPU clusters and CUDA environments",
      "Background in building internal developer platforms (IDP)",
      "Strong security and secrets management practices",
    ],
    fullPosting:
      "Anthropic's Platform team is the foundation on which frontier AI research happens. As a DevOps/Platform Engineer, you will ensure the reliability, scalability, and efficiency of the infrastructure that trains and serves Claude. Work at the cutting edge of AI infrastructure with world-class researchers.",
  },
];
